{% set name = "bhklab-project-template" %}
{% set version = "0.5.4" %}
{% set python_min = "3.12" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bhklab_project_template-{{ version }}.tar.gz
  sha256: 08bb7d3f5956269ebbef24f9315e2ff1de38a23a2b942249dab5e1e3a5caf265

build:
  entry_points:
    - bhk-project-template = bhklab_project_template.__init__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - rich >=14.0.0,<15
    - click >=8.2.0,<9
    - copier >=9.7.1,<10
    - rich-click

test:
  imports:
    - bhklab_project_template
    
  commands:
    - pip check
    - bhk-project-template --help
  requires:
    - pip
    - python {{ python_min }}


about:
  summary: A simple CLI tool to create new BHKLab projects from a template
  license: MIT
  license_file: LICENSE.md
  home: https://github.com/bhklab/bhklab-project-template
extra:
  recipe-maintainers:
    - jjjermiah
