context:
  name: bomctl
  version: 0.4.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/bomctl/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 8d361a0813de9aa65a366a1f8333004b2fa476981481c0c90e00ccaf74a01c58
    target_directory: src
  - url: https://gitlab.com/cznic/mathutil/-/raw/master/LICENSE
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    file_name: LICENSE.mathutil

build:
  script:
    - cd src
    - go-licenses save --ignore modernc.org/mathutil . --save_path ../library_licenses
    - if: win
      then: go build -v -o %LIBRARY_BIN%\bomctl.exe -ldflags="-s"
      else: go build -v -o $PREFIX/bin/bomctl -ldflags="-s -w"
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script: bomctl --help

about:
  homepage: https://github.com/bomctl/bomctl
  summary: Format agnostic SBOM tooling
  description: bomctl is format-agnostic Software Bill of Materials (SBOM) tooling, which is intended to bridge the gap between SBOM generation and SBOM analysis tools. It focuses on supporting more complex SBOM operations on multiple SBOM files that represent systems by being opinionated on only supporting the NTIA minimum fields or other fields supported by protobom.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
    - LICENSE.mathutil
  repository: https://github.com/bomctl/bomctl
  documentation: https://github.com/bomctl/bomctl

extra:
  recipe-maintainers:
    - xhochy
